targetScope = 'resourceGroup'

@description('Short prefix for all resource names, e.g. "recipes".')
param prefix string

@description('Azure region for all resources.')
param location string = resourceGroup().location

@description('Azure region for SQL — override if the main region is not accepting new SQL servers (RegionDoesNotAllowProvisioning).')
param sqlLocation string = location

@secure()
@description('SQL Server administrator password.')
param sqlAdminPassword string

@secure()
@description('Anthropic API key stored in Key Vault.')
param anthropicApiKey string

@secure()
@description('JWT signing key (base64, ≥ 32 bytes) — generated by infra/bootstrap.ps1, stored in Key Vault.')
param jwtSigningKey string

@secure()
@description('Bearer token for the MCP HTTP server — generated by infra/bootstrap.ps1, stored in Key Vault.')
param mcpServerToken string

var tags = {
  project: 'RecipesApp'
  environment: 'production'
}

// Key Vault name must be globally unique, max 24 chars, alphanumeric + hyphens
var kvPrefix = length(prefix) > 20 ? substring(prefix, 0, 20) : prefix
var kvName = '${kvPrefix}-kv'

// ── Monitoring ────────────────────────────────────────────────────────────────

module monitoring 'modules/monitoring.bicep' = {
  name: 'monitoring'
  params: {
    location: location
    prefix: prefix
    tags: tags
  }
}

// ── SQL ───────────────────────────────────────────────────────────────────────

module sql 'modules/sql.bicep' = {
  name: 'sql'
  params: {
    location: sqlLocation
    prefix: prefix
    tags: tags
    adminPassword: sqlAdminPassword
  }
}

// ── Static Web Apps ───────────────────────────────────────────────────────────

module swaReact 'modules/static-web-app.bicep' = {
  name: 'swa-react'
  params: {
    location: location
    name: '${prefix}-react'
    tags: tags
  }
}

module swaAngular 'modules/static-web-app.bicep' = {
  name: 'swa-angular'
  params: {
    location: location
    name: '${prefix}-angular'
    tags: tags
  }
}

// ── Key Vault ─────────────────────────────────────────────────────────────────

module keyVault 'modules/key-vault.bicep' = {
  name: 'key-vault'
  params: {
    location: location
    prefix: kvPrefix
    tags: tags
    anthropicApiKey: anthropicApiKey
    sqlConnectionString: sql.outputs.connectionString
    jwtSigningKey: jwtSigningKey
    mcpServerToken: mcpServerToken
  }
}

// ── App Service ───────────────────────────────────────────────────────────────

module appService 'modules/app-service.bicep' = {
  name: 'app-service'
  params: {
    location: location
    prefix: prefix
    tags: tags
    keyVaultName: keyVault.outputs.keyVaultName
    appInsightsConnectionString: monitoring.outputs.appInsightsConnectionString
    corsOrigins: [
      'https://${swaReact.outputs.hostname}'
      'https://${swaAngular.outputs.hostname}'
    ]
  }
}

// ── MCP Server ────────────────────────────────────────────────────────────────

module mcpServer 'modules/mcp-server.bicep' = {
  name: 'mcp-server'
  params: {
    location: location
    prefix: prefix
    tags: tags
    keyVaultName: keyVault.outputs.keyVaultName
    appInsightsConnectionString: monitoring.outputs.appInsightsConnectionString
    recipesApiHostname: appService.outputs.webAppHostname
    appServicePlanId: appService.outputs.appServicePlanId
  }
}

// ── Key Vault RBAC: grant App Service managed identity Secrets User ───────────

var keyVaultSecretsUserRoleId = '4633458b-17de-408a-b874-0445c86b69e6'

// kvName is a variable (computable at start) — required for scope/parent/name on role assignments and secrets
resource kvExisting 'Microsoft.KeyVault/vaults@2023-07-01' existing = {
  name: kvName
}

// Resources that target kvExisting need an explicit dependsOn on the keyVault
// module — Bicep doesn't infer dependencies through `existing` references, so
// without this they race the Key Vault creation and fail with ParentResourceNotFound.

resource kvRoleAssignment 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  scope: kvExisting
  name: guid(resourceGroup().id, kvName, 'api-kv-secrets-user')
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', keyVaultSecretsUserRoleId)
    principalId: appService.outputs.principalId
    principalType: 'ServicePrincipal'
  }
  dependsOn: [keyVault]
}

resource kvRoleAssignmentMcp 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  scope: kvExisting
  name: guid(resourceGroup().id, kvName, 'mcp-kv-secrets-user')
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', keyVaultSecretsUserRoleId)
    principalId: mcpServer.outputs.principalId
    principalType: 'ServicePrincipal'
  }
  dependsOn: [keyVault]
}

// ── SWA deployment tokens → Key Vault ─────────────────────────────────────────
// Stashed here so the deploy workflows can fetch them at runtime instead of
// requiring them as GitHub secrets.

resource secretReactDeploymentToken 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = {
  parent: kvExisting
  name: 'React-Deployment-Token'
  properties: {
    value: swaReact.outputs.deploymentToken
  }
  dependsOn: [keyVault]
}

resource secretAngularDeploymentToken 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = {
  parent: kvExisting
  name: 'Angular-Deployment-Token'
  properties: {
    value: swaAngular.outputs.deploymentToken
  }
  dependsOn: [keyVault]
}

// ── Outputs ───────────────────────────────────────────────────────────────────

output apiUrl string = 'https://${appService.outputs.webAppHostname}'
output apiHostname string = appService.outputs.webAppHostname
output mcpAppUrl string = 'https://${mcpServer.outputs.mcpAppHostname}'
output reactAppUrl string = 'https://${swaReact.outputs.hostname}'
output angularAppUrl string = 'https://${swaAngular.outputs.hostname}'
output keyVaultName string = keyVault.outputs.keyVaultName
output reactDeploymentToken string = swaReact.outputs.deploymentToken
output angularDeploymentToken string = swaAngular.outputs.deploymentToken
